# Notes
# - Look into node_module caching between steps

name: Publish Packages

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: number
      build-artifacts-name:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v4

      # Setup Node.js
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      # Install node_modules
      - name: Install dependencies
        run: npm ci

      # Install node_modules in all packages
      - name: Initialise all package node_modules
        run: npm run bootstrap

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.build-artifacts-name }} # Artifact name (must match upload name)
          path: ./packages

      - name: Write .npmrc file
        env:
          NPM_TOKEN: secrets.NPM_TOKEN
        run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc

      - name: Publish packages
        env:
          GH_TOKEN: secrets.GH_TOKEN
        run: npm run semantic-release
